### ISSUE TITLE
Using attributes in galleryview tag doesn't affect plugin (and page) output

### ISSUE THREAD

**Issue by iamweird** [hybridindie/WordPress-Nextgen-GalleryView#5]
Version affected: NextGen GalleryView 0.5.
Steps needed to reproduce the bug:
1. Download the plugin v.0.5 from http://wordpress.org/extend/plugins/wordpress-nextgen-galleryview/ , unzip and activate.
2. Create a sample gallery and add at least one image to it. Let it be gallery #1.
3. Create a page and insert i.e. the following code: [galleryview id=1 filmstripPosition=left](default is bottom).
4. Go to the gallery page and see filmstrip still at the bottom.

I guess it's caused by CamelCase used in attribute names. See http://codex.wordpress.org/Shortcode_API#Attributes (end of section, Important Tip note) for details. Hope this helps.

**Comment by hybridindie** [comment]
Update pushed

**Comment by iamweird** [comment]
Thank you very much for such a quick fix!
